--------------------------------------------------------
--  Arquivo criado - terça-feira-agosto-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTIGO
--------------------------------------------------------

  CREATE TABLE "KAY"."ARTIGO" 
   (	"MAT" VARCHAR2(4 BYTE), 
	"TITULO" VARCHAR2(80 BYTE), 
	"NOTA" NUMBER(4,2), 
	"IDIOMA" VARCHAR2(15 BYTE) DEFAULT 'PORTUGUES', 
	"COD" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESCREVE
--------------------------------------------------------

  CREATE TABLE "KAY"."ESCREVE" 
   (	"CPF" VARCHAR2(4 BYTE), 
	"MAT" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTO
--------------------------------------------------------

  CREATE TABLE "KAY"."EVENTO" 
   (	"COD" VARCHAR2(4 BYTE), 
	"NOME" VARCHAR2(80 BYTE), 
	"SIGLA" VARCHAR2(10 BYTE), 
	"ANO" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PESQUISADOR
--------------------------------------------------------

  CREATE TABLE "KAY"."PESQUISADOR" 
   (	"CPF" VARCHAR2(4 BYTE), 
	"NOME" VARCHAR2(80 BYTE), 
	"INSTITUICAO" VARCHAR2(40 BYTE), 
	"NASCIMENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into KAY.ARTIGO
SET DEFINE OFF;
REM INSERTING into KAY.ESCREVE
SET DEFINE OFF;
REM INSERTING into KAY.EVENTO
SET DEFINE OFF;
REM INSERTING into KAY.PESQUISADOR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ESCREVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KAY"."ESCREVE_PK" ON "KAY"."ESCREVE" ("CPF", "MAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AK_USU_CPF
--------------------------------------------------------

  CREATE UNIQUE INDEX "KAY"."AK_USU_CPF" ON "KAY"."PESQUISADOR" ("NOME", "NASCIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ARTIGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "KAY"."PK_ARTIGO" ON "KAY"."ARTIGO" ("MAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "KAY"."PK_USUARIOS" ON "KAY"."PESQUISADOR" ("CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARTIGO
--------------------------------------------------------

  ALTER TABLE "KAY"."ARTIGO" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "KAY"."ARTIGO" MODIFY ("NOTA" NOT NULL ENABLE);
  ALTER TABLE "KAY"."ARTIGO" ADD CONSTRAINT "CHK_ART_NOTA" CHECK (NOTA BETWEEN 0 AND 10) ENABLE;
  ALTER TABLE "KAY"."ARTIGO" ADD CONSTRAINT "PK_ARTIGO" PRIMARY KEY ("MAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENTO
--------------------------------------------------------

  ALTER TABLE "KAY"."EVENTO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "KAY"."EVENTO" MODIFY ("SIGLA" NOT NULL ENABLE);
  ALTER TABLE "KAY"."EVENTO" ADD PRIMARY KEY ("COD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KAY"."EVENTO" ADD UNIQUE ("SIGLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESCREVE
--------------------------------------------------------

  ALTER TABLE "KAY"."ESCREVE" ADD CONSTRAINT "ESCREVE_PK" PRIMARY KEY ("CPF", "MAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PESQUISADOR
--------------------------------------------------------

  ALTER TABLE "KAY"."PESQUISADOR" MODIFY ("NOME" CONSTRAINT "NN_PESQ_NOME" NOT NULL ENABLE);
  ALTER TABLE "KAY"."PESQUISADOR" MODIFY ("INSTITUICAO" NOT NULL ENABLE);
  ALTER TABLE "KAY"."PESQUISADOR" ADD CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("CPF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KAY"."PESQUISADOR" ADD CONSTRAINT "AK_USU_CPF" UNIQUE ("NOME", "NASCIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARTIGO
--------------------------------------------------------

  ALTER TABLE "KAY"."ARTIGO" ADD CONSTRAINT "FK_ART_EVE" FOREIGN KEY ("COD")
	  REFERENCES "KAY"."EVENTO" ("COD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESCREVE
--------------------------------------------------------

  ALTER TABLE "KAY"."ESCREVE" ADD CONSTRAINT "ESCREVEPESQUISADOR_FK" FOREIGN KEY ("CPF")
	  REFERENCES "KAY"."PESQUISADOR" ("CPF") ON DELETE CASCADE ENABLE;
  ALTER TABLE "KAY"."ESCREVE" ADD CONSTRAINT "ESCREVEARTIGO_FK" FOREIGN KEY ("MAT")
	  REFERENCES "KAY"."ARTIGO" ("MAT") ON DELETE CASCADE ENABLE;
